# docker-compose -f minio-compose.yml up

version: '2'

services:
  minio:
    image: minio/minio
    volumes:
      - minioVolume:/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: accessKey
      MINIO_SECRET_KEY: secretKey
    command: server http://minio/export

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minioVolume1:
